name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: qulzumayeshaawan7-tech
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/github-contribution-grid-snake.svg"
          message: "Update contribution snake"
          push: true
